import { useEffect, useState, type ChangeEvent } from "react";
import { api } from "./api/client";
import { Shell } from "./components/layout";
import { Benchmark, Dataset, Generation, Optimization, Overview, Results, Validation } from "./pages";
import type { DatasetAnalysis, GenerationPlan, Page, PipelineJob, PipelineResult } from "./types/api";

export default function App() {
  const [page, setPage] = useState<Page>("Overview"); const [file, setFile] = useState<File | null>(null); const [analysis, setAnalysis] = useState<DatasetAnalysis | null>(null); const [plan, setPlan] = useState<GenerationPlan | null>(null); const [preview, setPreview] = useState<Record<string, unknown>[]>([]); const [result, setResult] = useState<PipelineResult | null>(null); const [job, setJob] = useState<PipelineJob | null>(null); const [target, setTarget] = useState(""); const [error, setError] = useState<string | null>(null); const [online, setOnline] = useState(false);
  useEffect(() => { api.health().then(() => setOnline(true)).catch(() => setOnline(false)); }, []);
  useEffect(() => { if (!job || !["queued", "running"].includes(job.status)) return; const id = window.setInterval(() => api.job(job.job_id).then((next) => { setJob(next); if (next.status === "completed" && next.result) { setResult(next.result); setPreview(next.synthetic_preview ?? []); setPage("Results"); } if (next.status === "failed") setError(next.error ?? "Pipeline execution failed."); }).catch((err: Error) => setError(err.message)), 1400); return () => window.clearInterval(id); }, [job]);
  const analyzeFile = async (nextFile: File, nextTarget: string, auto = false) => { setError(null); try { const response = await api.plan(nextFile, nextTarget === "__auto__" ? null : nextTarget || null, auto || nextTarget === "__auto__"); setAnalysis(response.analysis); setPlan(response.plan); setPreview(response.preview); if (response.analysis.target_column && !nextTarget) setTarget(response.analysis.target_column); } catch (err) { setError(err instanceof Error ? err.message : "Analysis failed."); } };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => { const next = event.target.files?.[0] ?? null; if (!next) return; setFile(next); setAnalysis(null); setPlan(null); setResult(null); setPreview([]); setTarget(""); void analyzeFile(next, ""); };
  const loadSample = async (sample: "labeled" | "unlabeled") => { setError(null); try { const next = await api.sample(sample); const nextTarget = sample === "labeled" ? "target" : ""; setFile(next); setAnalysis(null); setPlan(null); setResult(null); setPreview([]); setTarget(nextTarget); await analyzeFile(next, nextTarget); } catch (err) { setError(err instanceof Error ? err.message : "Sample dataset is unavailable."); } };
  const analyze = async (auto = false) => { if (file) await analyzeFile(file, target, auto); };
  const run = async () => { if (!file) return; setError(null); try { setJob(await api.startRun(file, { targetColumn: target === "__auto__" ? null : target || null, autoDetect: target === "__auto__", maxIterations: 5, preferredGenerator: plan?.generator, enableLlm: true })); } catch (err) { setError(err instanceof Error ? err.message : "Could not start pipeline."); } };
  const ctx = { file, analysis, plan, result, preview, job, target, setTarget, onFile, loadSample, analyze, run, error };
  const content = { Overview: <Overview ctx={ctx} go={setPage} />, Dataset: <Dataset ctx={ctx} />, Generation: <Generation ctx={ctx} />, Validation: <Validation ctx={ctx} />, Benchmark: <Benchmark ctx={ctx} />, Optimization: <Optimization ctx={ctx} />, Results: <Results ctx={ctx} /> }[page];
  return <Shell page={page} setPage={setPage} filename={file?.name ?? result?.dataset_filename ?? undefined} status={job?.status ?? (result ? "completed" : "ready")} online={online}>{error && <div className="mb-5 rounded-md border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}{content}</Shell>;
}
